# Generated by Django 3.2.15 on 2022-10-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0005_alter_todolist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
